---
title: ""
---
<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="site_libs/academicons-1.9.1/css/academicons.min.css"/>

## Leadership, Service, & Advocacy
  
  &nbsp;
  
### "Human rights violations are not accidents; they are not random in distribution or effect. Rights violations are, rather, symptoms of deeper pathologies of power and are linked intimately to the social conditions that so often determine who will suffer abuse and who will be shielded from harm." 

<center>
##### - Paul Farmer, Pathologies of Power: Health, Human Rights, and the New War on the Poor 
</center>

  &nbsp;


##### It is with this quote that Paul Farmer opens his discussion on structural violence. The idea of structural violence emphasizes that issues of inequity and human rights abuse are not merely interpersonal; they are systematic in nature and designed to benefit those in power (i.e. white supremacy) while discriminating and exploiting groups based on race, religion, ability, gender, sexuality, income, and many more identities. Naming it is important, but it is even more important to practice leadership that champions *listening*, *inclusivity*, *community*, and *humility*. Bear witness to these atrocities and seek to use your privilege and power to create meaningful change and uplift communities globally.

  &nbsp;

##### I include this here in hope that you will reflect on your own leadership and ask: *how can I be of service?*



  &nbsp;
  
  &nbsp;
  
  &nbsp;
  
  &nbsp;
  
  &nbsp;



